export const SEO = {
  title: "Café",
  description: "Descubre el mundo del café: recetas, métodos de preparación y curiosidades.",
  author: "edard3v",
  img: "https://res.cloudinary.com/dzuo8j1qg/image/upload/v1741119204/coffee/v2vg7zep3zblmhap1uq3.jpg",
  keywords: [
    "café",
    "coffee",
    "barista",
    "recetas de café",
    "preparación de café",
    "tipos de café",
    "granos de café",
    "historia del café",
    "mejores cafeterías",
    "coffee lovers",
    "cultura del café",
    "métodos de extracción",
    "cafés especiales",
  ],
  base_url: "https://coffee-aey.pages.dev",
};
